# .streamlit/config.toml
[client]
toolbarMode = false

# .streamlit/config.toml
[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "chatbot.cel.somethings.michaelaraona.web.id"
serverPort = 443